services:
  mic-plot-generator:
    image: ghcr.io/staljabro/mic-plot-generator:latest
    pull_policy: always
    container_name: mic-plot-generator
    ports:
      - "8087:80"
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/staljabro/Mic-Plot-Generator/main/public/icon.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8087]"
